### ISSUE TITLE
Plumbing rule not robust enough

### ISSUE THREAD

**Issue by lelysses** [pellertson/gacme#1]
been meaning to say something about this since the rc version dropped. the plumbing rules don't match a lot of valid URLs. the two consequences I've noticed so far are: 

1) any paths with periods in them aren't matched, which wouldn't seem to be that huge of a problem since gacme can't handle binary files, so I guess this prevents you from accidentally dumping binary data from `gemini://somesite.org/video.mp4` into an acme buffer, but it also means any sites that don't just serve the index of a directory but instead link to one of several .gmi files that exists in a given directory (e.g. `gemini://gemini.circumlunar.space/docs/specification.gmi`, any files served as `text/raw`) won't work, even though gacme is otherwise well-equipped to properly display them.

2) any paths with tildes in them aren't matched, which for gemini in particular is more of an issue than it at first seems, because the tilde/pubnix community was an early adopter of gemini, and a lot of pubnixes link to user sites with something like `gemini://tilde.pink/~tiwesdaeg/` or `gemini://envs.net/~creme/`.

there are probably other things the plumbing rules miss but i haven't run afoul of them yet. i don't remember where in the URI RFC the BNF is for valid hosts and paths so i haven't been able to compare.

at the moment i'm using this plumbing rule to avoid at least the two issues i mentioned:

```
type is text
data matches 'gemini://([a-zA-Z0-9_\-.]+[.:][a-zA-Z0-9_@\-]+)(/?[a-zA-Z0-9/_\-~.]*)'
plumb to web
plumb start gacme $0 $1 $2
```

but as i say there are likely other edge-cases missing idk

(this is so awesome though)

**Comment by pellertson** [comment]
I've noticed this on my end as well. I've actually made similar changes on my end, but I've forgotten to push them up until I saw this issue. :joy: Thanks for this!
